---

- name: Install apt_repository module dependency.
  pip:
    name: python-apt
    state: present

- name: Enable universe repository
  apt_repository:
    repo: deb http://archive.ubuntu.com/ubuntu 16.04 universe
    state: present

- name: Update repositories.
  apt:
    update_cache: True
